/*
 * ER/Studio 8.0 SQL Code Generation
 * Company :      RMG Informática
 * Project :      Quermesse.DM1
 * Author :       rogeriomgigliotti@hotmail.com
 *
 * Date Created : Wednesday, August 09, 2023 22:22:25
 * Target DBMS : Microsoft SQL Server 2008
 */

/* 
 * TABLE: ESTOQUE 
 */

CREATE TABLE ESTOQUE(
    CD_ESTOQUE                 numeric(10, 0)    IDENTITY(1,1),
    CD_EVENTOPRODUTO           numeric(10, 0)    NULL,
    CD_USUARIO                 numeric(10, 0)    NULL,
    CD_TIPOMOVIMENTOESTOQUE    numeric(10, 0)    NULL,
    DT_MOVIMENTO               datetime          NULL,
    QT_MOVIMENTO               numeric(10, 0)    NULL,
    CONSTRAINT ESTOQUE_PK PRIMARY KEY NONCLUSTERED (CD_ESTOQUE)
)
go



IF OBJECT_ID('ESTOQUE') IS NOT NULL
    PRINT '<<< CREATED TABLE ESTOQUE >>>'
ELSE
    PRINT '<<< FAILED CREATING TABLE ESTOQUE >>>'
go

/* 
 * TABLE: EVENTO 
 */

CREATE TABLE EVENTO(
    CD_EVENTO    numeric(10, 0)    IDENTITY(1,1),
    DS_EVENTO    varchar(100)      NOT NULL,
    DT_EVENTO    datetime          NULL,
    CONSTRAINT EVENTO_PK PRIMARY KEY NONCLUSTERED (CD_EVENTO)
)
go



IF OBJECT_ID('EVENTO') IS NOT NULL
    PRINT '<<< CREATED TABLE EVENTO >>>'
ELSE
    PRINT '<<< FAILED CREATING TABLE EVENTO >>>'
go

/* 
 * TABLE: EVENTOPRODUTO 
 */

CREATE TABLE EVENTOPRODUTO(
    CD_EVENTOPRODUTO    numeric(10, 0)    IDENTITY(1,1),
    CD_EVENTO           numeric(10, 0)    NULL,
    CD_PRODUTO          numeric(10, 0)    NULL,
    VL_PRODUTO          numeric(18, 2)    NULL,
    CONSTRAINT EVENTOPRODUTO_PK PRIMARY KEY NONCLUSTERED (CD_EVENTOPRODUTO)
)
go



IF OBJECT_ID('EVENTOPRODUTO') IS NOT NULL
    PRINT '<<< CREATED TABLE EVENTOPRODUTO >>>'
ELSE
    PRINT '<<< FAILED CREATING TABLE EVENTOPRODUTO >>>'
go

/* 
 * TABLE: PRODUTO 
 */

CREATE TABLE PRODUTO(
    CD_PRODUTO        numeric(10, 0)    IDENTITY(1,1),
    NM_PRODUTO        varchar(100)      NOT NULL,
    CD_TIPOPRODUTO    numeric(10, 0)    NOT NULL,
    ATIVO             numeric(1, 0)     NOT NULL,
    CONSTRAINT PRODUTO_PK PRIMARY KEY NONCLUSTERED (CD_PRODUTO)
)
go



IF OBJECT_ID('PRODUTO') IS NOT NULL
    PRINT '<<< CREATED TABLE PRODUTO >>>'
ELSE
    PRINT '<<< FAILED CREATING TABLE PRODUTO >>>'
go

/* 
 * TABLE: TIPOMOVIMENTOESTOQUE 
 */

CREATE TABLE TIPOMOVIMENTOESTOQUE(
    CD_TIPOMOVIMENTOESTOQUE    numeric(10, 0)    NOT NULL,
    DS_TIPOMOVIMENTOESTOQUE    varchar(100)      NOT NULL,
    CONSTRAINT TIPOMOVIMENTOESTOQUE_PK PRIMARY KEY NONCLUSTERED (CD_TIPOMOVIMENTOESTOQUE)
)
go



IF OBJECT_ID('TIPOMOVIMENTOESTOQUE') IS NOT NULL
    PRINT '<<< CREATED TABLE TIPOMOVIMENTOESTOQUE >>>'
ELSE
    PRINT '<<< FAILED CREATING TABLE TIPOMOVIMENTOESTOQUE >>>'
go

/* 
 * TABLE: TIPOPRODUTO 
 */

CREATE TABLE TIPOPRODUTO(
    CD_TIPOPRODUTO    numeric(10, 0)    IDENTITY(1,1),
    DS_TIPOPRODUTO    varchar(100)      NOT NULL,
    CONSTRAINT TIPOPRODUTO_PK PRIMARY KEY NONCLUSTERED (CD_TIPOPRODUTO)
)
go



IF OBJECT_ID('TIPOPRODUTO') IS NOT NULL
    PRINT '<<< CREATED TABLE TIPOPRODUTO >>>'
ELSE
    PRINT '<<< FAILED CREATING TABLE TIPOPRODUTO >>>'
go

/* 
 * TABLE: TIPOUSUARIO 
 */

CREATE TABLE TIPOUSUARIO(
    CD_TIPOUSUARIO    numeric(10, 0)    NOT NULL,
    DS_TIPOUSUARIO    varchar(100)      NOT NULL,
    CONSTRAINT TIPOUSUARIO_PK PRIMARY KEY NONCLUSTERED (CD_TIPOUSUARIO)
)
go



IF OBJECT_ID('TIPOUSUARIO') IS NOT NULL
    PRINT '<<< CREATED TABLE TIPOUSUARIO >>>'
ELSE
    PRINT '<<< FAILED CREATING TABLE TIPOUSUARIO >>>'
go

/* 
 * TABLE: USUARIO 
 */

CREATE TABLE USUARIO(
    CD_USUARIO        numeric(10, 0)    IDENTITY(1,1),
    NM_USUARIO        varchar(100)      NOT NULL,
    CD_TIPOUSUARIO    numeric(10, 0)    NULL,
    DS_LOGIN          varchar(100)      NULL,
    DS_SENHA          varchar(100)      NULL,
    ATIVO             numeric(1, 0)     NOT NULL,
    CONSTRAINT USUARIO_PK PRIMARY KEY NONCLUSTERED (CD_USUARIO)
)
go



IF OBJECT_ID('USUARIO') IS NOT NULL
    PRINT '<<< CREATED TABLE USUARIO >>>'
ELSE
    PRINT '<<< FAILED CREATING TABLE USUARIO >>>'
go

/* 
 * TABLE: VENDA 
 */

CREATE TABLE VENDA(
    CD_VENDA            numeric(10, 0)    IDENTITY(1,1),
    CD_EVENTOPRODUTO    numeric(10, 0)    NULL,
    CD_USUARIO          numeric(10, 0)    NULL,
    DT_VENDA            datetime          NULL,
    QT_VENDA            numeric(10, 0)    NULL,
    VL_VENDA            numeric(18, 2)    NULL,
    CONSTRAINT VENDA_PK PRIMARY KEY NONCLUSTERED (CD_VENDA)
)
go



IF OBJECT_ID('VENDA') IS NOT NULL
    PRINT '<<< CREATED TABLE VENDA >>>'
ELSE
    PRINT '<<< FAILED CREATING TABLE VENDA >>>'
go

/* 
 * TABLE: ESTOQUE 
 */

ALTER TABLE ESTOQUE ADD CONSTRAINT ESTOQUE_EVENTOPRODUTO_FK 
    FOREIGN KEY (CD_EVENTOPRODUTO)
    REFERENCES EVENTOPRODUTO(CD_EVENTOPRODUTO)
go

ALTER TABLE ESTOQUE ADD CONSTRAINT ESTOQUE_TIPOMOVIMENTOESTOQUE_FK 
    FOREIGN KEY (CD_TIPOMOVIMENTOESTOQUE)
    REFERENCES TIPOMOVIMENTOESTOQUE(CD_TIPOMOVIMENTOESTOQUE)
go

ALTER TABLE ESTOQUE ADD CONSTRAINT ESTOQUE_USUARIO_FK 
    FOREIGN KEY (CD_USUARIO)
    REFERENCES USUARIO(CD_USUARIO)
go


/* 
 * TABLE: EVENTOPRODUTO 
 */

ALTER TABLE EVENTOPRODUTO ADD CONSTRAINT EVENTOPRODUTO_EVENTO_FK 
    FOREIGN KEY (CD_EVENTO)
    REFERENCES EVENTO(CD_EVENTO)
go

ALTER TABLE EVENTOPRODUTO ADD CONSTRAINT EVENTOPRODUTO_PRODUTO_FK 
    FOREIGN KEY (CD_PRODUTO)
    REFERENCES PRODUTO(CD_PRODUTO)
go


/* 
 * TABLE: PRODUTO 
 */

ALTER TABLE PRODUTO ADD CONSTRAINT PRODUTO_TIPOPRODUTO_FK 
    FOREIGN KEY (CD_TIPOPRODUTO)
    REFERENCES TIPOPRODUTO(CD_TIPOPRODUTO)
go


/* 
 * TABLE: USUARIO 
 */

ALTER TABLE USUARIO ADD CONSTRAINT USUARIO_TIPOUSUARIO_FK 
    FOREIGN KEY (CD_TIPOUSUARIO)
    REFERENCES TIPOUSUARIO(CD_TIPOUSUARIO)
go


/* 
 * TABLE: VENDA 
 */

ALTER TABLE VENDA ADD CONSTRAINT VENDA_EVENTOPRODUTO_FK 
    FOREIGN KEY (CD_EVENTOPRODUTO)
    REFERENCES EVENTOPRODUTO(CD_EVENTOPRODUTO)
go

ALTER TABLE VENDA ADD CONSTRAINT VENDA_USUARIO_FK 
    FOREIGN KEY (CD_USUARIO)
    REFERENCES USUARIO(CD_USUARIO)
go