INSERT INTO TIPOPRODUTO (DS_TIPOPRODUTO)
SELECT 'Bebidas' UNION ALL
SELECT 'Comidas'
GO

INSERT INTO TIPOUSUARIO (CD_TIPOUSUARIO, DS_TIPOUSUARIO)
SELECT 1, 'Administrador' UNION ALL
SELECT 2, 'Vendas'
GO

INSERT INTO TIPOMOVIMENTOESTOQUE (CD_TIPOMOVIMENTOESTOQUE, DS_TIPOMOVIMENTOESTOQUE)
SELECT 1, 'Entrada' UNION ALL
SELECT 2, 'Estorno'
GO

INSERT INTO PRODUTO (NM_PRODUTO, CD_TIPOPRODUTO, ATIVO)
SELECT 'Cerveja - Garrafa 600ml', 1, 1 UNION ALL
SELECT 'Refrigerante', 1, 1 UNION ALL
SELECT 'Água', 1, 1 UNION ALL
SELECT 'Vinho – Copo 300ml', 1, 1 UNION ALL
SELECT 'Milk Shake - Tradicional', 1, 1 UNION ALL
SELECT 'Milk Shake - Vinho', 1, 1 UNION ALL          
SELECT 'Arroz', 2, 1 UNION ALL
SELECT 'Batata Frita', 2, 1 UNION ALL
SELECT 'Cachorro Quente', 2, 1 UNION ALL
SELECT 'Coxinha', 2, 1 UNION ALL
SELECT 'Espetinho', 2, 1 UNION ALL            
SELECT 'Fogaça', 2, 1 UNION ALL
SELECT 'Frango Assado', 2, 1 UNION ALL
SELECT 'Mandioca Frita', 2, 1 UNION ALL
SELECT 'Nhoque', 2, 1 UNION ALL
SELECT 'Pão', 2, 1 UNION ALL
SELECT 'Polenta c/ Molho de Carne', 2, 1 UNION ALL
SELECT 'Polenta Frita', 2, 1 UNION ALL
SELECT 'Pastel', 2, 1 UNION ALL
SELECT 'Vinagrete', 2, 1
GO

INSERT INTO USUARIO (NM_USUARIO, CD_TIPOUSUARIO, DS_LOGIN, DS_SENHA, ATIVO)
SELECT 'Administrador', 1, 'admin', '@dm!n', 1 UNION ALL
SELECT 'Vendas', 2, 'vendas', 'v&nd@s', 1
GO